### ISSUE TITLE
Error after installation

### ISSUE THREAD

**Issue by TurtleInTheSky** [Joseph-Y/godmode#4]
Start Anki, browse desk and: 

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.41 (312fa278) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-03-07 07:01:09

Caught exception:
Traceback (most recent call last):
  File "aqt\webview.py", line 36, in cmd
  File "aqt\webview.py", line 135, in _onCmd
  File "aqt\webview.py", line 580, in _onBridgeCmd
  File "aqt\toolbar.py", line 169, in _linkHandler
  File "aqt\toolbar.py", line 187, in _browseLinkHandler
  File "aqt\main.py", line 1067, in onBrowse
  File "aqt\__init__.py", line 101, in open
  File "aqt\browser.py", line 469, in __init__
  File "aqt\browser.py", line 531, in setupMenus
  File "aqt\hooks_gen.py", line 526, in __call__
  File "anki\hooks.py", line 34, in runHook
  File "C:\Users\allan\AppData\Roaming\Anki2\addons21\1508677152\custom_shortcuts.py", line 354, in cs_browser_setupShortcuts
    f.previewButton.setShortcut(config_scuts["window_browser preview"])
AttributeError: 'Ui_Dialog' object has no attribute 'previewButton'

**Comment by Joseph-Y** [comment]
Thanks for reporting this issue. Seems to be due to changes with the newest Anki version (2.1.41). I've restricted downloads to newer versions until I can look into this, but it's not a priority for me because I use an older Anki version. To anyone reading this, I'd appreciate any contributions toward a solution on Github.

**Comment by mrmo123** [comment]
Hi, I fixed the issue on my end by removing two lines of code in custom_shortcuts.py

Line 354: f.previewButton.setShortcut(config_scuts["window_browser preview"])
Line 366: f.actionTags.setShortcut(config_scuts["window_browser filter"])

Thanks for a wonderful add-on!

Anki version ⁨2.1.43
